name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]  # change if your default branch is different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./   # replace with build output dir (e.g., ./dist or ./build)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

