name: Deploy Website to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Remove these lines if you don't need Node.js:
      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      # - name: Install dependencies
      #   run: npm install

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./

